name: Azure Terraform CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # Defaults - update these or provide repository secrets if needed
  PREFIX: gha2
  LOCATION: swedencentral
  IMAGE_NAME: ghapp
  TAG: ${{ github.sha }}

  # Optionally set these secrets in the repo to use an existing ACR
  # AZURE_ACR_NAME and AZURE_ACR_RG are expected as repository secrets

jobs:
  resolve-and-build:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}
      ACR_RG: ${{ secrets.AZURE_ACR_RG }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      ACR_ID: ${{ secrets.AZURE_ACR_ID }}
    outputs:
      registry: ${{ steps.set-outputs.outputs.registry }}
      acr_name: ${{ steps.set-outputs.outputs.acr_name }}
      acr_rg: ${{ steps.set-outputs.outputs.acr_rg }}
      image_tag: ${{ steps.set-outputs.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Resolve ACR login server (using provided ACR)
        id: resolve
        run: |
          set -euo pipefail

          fail() {
            echo "Error: $*" >&2
            exit 1
          }

          echo "Resolving ACR login server..."

          lookup_registry() {
            local name="$1"
            local rg="${2-}"
            if [ -n "$rg" ]; then
              az acr show -n "$name" --resource-group "$rg" --query loginServer -o tsv || true
            else
              az acr show -n "$name" --query loginServer -o tsv || true
            fi
          }

          if [ -n "${ACR_ID-}" ]; then
            if [[ "$ACR_ID" == /subscriptions/* ]]; then
              echo "Parsing ACR resource id: $ACR_ID"
              ACR_NAME=$(basename "$ACR_ID")
              ACR_RG=$(echo "$ACR_ID" | sed -n 's|.*/resourceGroups/\([^/]*\)/.*|\1|p')
              [ -n "$ACR_NAME" ] || fail "could not determine registry name from id"
              echo "Parsed name=$ACR_NAME resourceGroup=$ACR_RG"
              REGISTRY=$(lookup_registry "$ACR_NAME" "$ACR_RG")
            else
              echo "ACR_ID provided but does not look like a resource id; treating as registry name: $ACR_ID"
              ACR_NAME="$ACR_ID"
              REGISTRY=$(lookup_registry "$ACR_NAME" "${ACR_RG-}")
            fi
          else
            [ -n "${ACR_NAME-}" ] || fail "provide AZURE_ACR_NAME or AZURE_ACR_ID as a secret"
            echo "Using ACR name: $ACR_NAME (resource group: ${ACR_RG-})"
            REGISTRY=$(lookup_registry "$ACR_NAME" "${ACR_RG-}")
          fi

          if [ -z "${REGISTRY-}" ] || [ -z "$REGISTRY" ]; then
            fail "could not resolve loginServer for ACR name='$ACR_NAME' (rg='${ACR_RG-}') - ensure the name and resource group are correct and the logged-in Azure identity has permission to read the registry"
          fi

          echo "Resolved registry: $REGISTRY"
          echo "registry=$REGISTRY" >> $GITHUB_OUTPUT
          echo "acr_name=$ACR_NAME" >> $GITHUB_OUTPUT
          echo "acr_rg=${ACR_RG-}" >> $GITHUB_OUTPUT
          echo "image_tag=${{ env.TAG }}" >> $GITHUB_OUTPUT

      - name: Build and push image to ACR
        run: |
          REGISTRY=${{ steps.resolve.outputs.registry }}
          ACR_NAME=${{ steps.resolve.outputs.acr_name }}
          ACR_RG=${{ steps.resolve.outputs.acr_rg }}

          if [ -n "$ACR_USERNAME" ] && [ -n "$ACR_PASSWORD" ]; then
            echo "$ACR_PASSWORD" | docker login $REGISTRY --username $ACR_USERNAME --password-stdin
          else
            az acr login -n $ACR_NAME
          fi
          docker build -t $REGISTRY/${{ env.IMAGE_NAME }}:${{ env.TAG }} -f Dockerfile .
          docker push $REGISTRY/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: set-outputs
        id: set-outputs
        run: |
          # pass through values already set in $GITHUB_OUTPUT by resolve step
          echo "registry=${{ steps.resolve.outputs.registry }}" >> $GITHUB_OUTPUT
          echo "acr_name=${{ steps.resolve.outputs.acr_name }}" >> $GITHUB_OUTPUT
          echo "acr_rg=${{ steps.resolve.outputs.acr_rg }}" >> $GITHUB_OUTPUT
          echo "image_tag=${{ env.TAG }}" >> $GITHUB_OUTPUT

  terraform-init:
    needs: resolve-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

  terraform-plan:
    needs: [resolve-and-build, terraform-init]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Terraform Init (plan job)
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -out=tfplan \
            -var="prefix=${{ env.PREFIX }}" \
            -var="location=${{ env.LOCATION }}" \
            -var="image_name=${{ env.IMAGE_NAME }}" \
            -var="image_tag=${{ env.TAG }}" \
            -var="use_existing_acr=true" \
            -var="existing_acr_name=${{ needs['resolve-and-build'].outputs.acr_name }}" \
            -var="existing_acr_rg=${{ needs['resolve-and-build'].outputs.acr_rg }}" \
            -var="existing_acr_id=${{ secrets.AZURE_ACR_ID }}" \
            -var="container_port=80" \
            -var="acr_admin_username=${{ secrets.ACR_USERNAME }}" \
            -var="acr_admin_password=${{ secrets.ACR_PASSWORD }}"

      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan

      - name: Check for Terraform lockfile
        id: check_lock
        run: |
          if [ -f terraform/.terraform.lock.hcl ]; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload Terraform lockfile
        if: steps.check_lock.outputs.found == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: tf_lock
          path: terraform/.terraform.lock.hcl

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5


      - name: Download Terraform lockfile
        id: download_lock
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: tf_lock
          path: terraform

      - name: Check downloaded lockfile
        run: |
          if [ -f terraform/.terraform.lock.hcl ]; then
            echo "Lockfile downloaded"
          else
            echo "No lockfile downloaded; proceeding without lockfile — provider selections may differ from the plan"
          fi

      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform

      - name: Terraform Init (apply job)
        run: |
          cd terraform
          # use the downloaded .terraform.lock.hcl so provider selections match the plan
          terraform init -input=false

      - name: Terraform Apply (manual approval required via environment)
        run: |
          cd terraform
          terraform apply -auto-approve tfplan
